---
version: '3.7'

volumes:
    localBindApp:
        driver: local
        driver_opts:
            type: none
            device: $PWD/${LOCAL_SRC}
            o: bind

services:

    webserver:
        volumes:
            # - type: bind
            #   source: ./nginx/docker-entrypoint.sh
            #   target: /entrypoint.sh
            #   read_only: true
            - type: volume
              source: localBindApp
              target: ${REMOTE_SRC}

    app:
        volumes:
            # # Used [:delegated] or [:cached] mode here on docker for MAC for faster disk I/O
            - ${LOCAL_SRC}:${REMOTE_SRC}:delegated
            - ./app/docker-entrypoint.sh:/entrypoint.sh:ro
            # - ./app/config/php.ini-development.ini:/usr/local/etc/php/php.ini:ro
            # - ./app/config/extensions/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
            # - ./app/config/extensions/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

    queue:
        volumes:
            # - type: bind
            #   source: ./queue/docker-entrypoint.sh
            #   target: /start.sh
            #   read_only: true
            - ${LOCAL_SRC}:${REMOTE_SRC}:delegated

    scheduler:
        volumes:
            # - type: bind
            #   source: ./scheduler/docker-entrypoint.sh
            #   target: /start.sh
            #   read_only: true
            - ${LOCAL_SRC}:${REMOTE_SRC}:delegated
